server:
  port: 8080
  servlet:
    context-path: /event-service/api
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console